inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

