require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3.x
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'