name: Ruby CI

on: push

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: 5xtraining_backend_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: john9966
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
      with:
        ruby-version: '3.0.0'
        bundler-cache: true

    - name: Set up PostgreSQL
      run: |
        sudo apt-get install -y libpq-dev
        cp config/database.yml.ci config/database.yml
      env:
        RAILS_ENV: test

    - name: Create and migrate database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:john9966@localhost:5433/5xtraining_backend_test

    - name: Run tests
      run: bundle exec rspec
      env:
        RAILS_ENV: test
        POSTGRES_DB: 5xtraining_backend_test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: john9966
        DATABASE_URL: postgres://postgres:john9966@localhost:5433/5xtraining_backend_test
